//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace çalışanyönetimsistemi.Models.Baglantisql
{
    using System;
    using System.Collections.Generic;
    
    public partial class avanstalep
    {
        public int avanstalepid { get; set; }
        public string tarih { get; set; }
        public string adsoyad { get; set; }
        public string avansmiktar { get; set; }
        public string açıklama { get; set; }
    }
}
