//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace çalışanyönetimsistemi.Models.Baglantisql
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletişim
    {
        public int iletişimid { get; set; }
        public string ad { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string mesaj { get; set; }
    }
}
